### ISSUE TITLE
validation: layout configurations should always pass

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar-tooling#14]
Either we should demand that layout entries in pages do not have a `features` entry, or simply have them pass by default.

**Comment by jpommerening** [comment]
So there are layout configurations that fail validation but should pass? Can you give an example?

**Comment by x1B** [comment]
I'd have to look into it again, but IIRC the validation fails everytime a layout with an empty `features` object is referenced from a page.

**Comment by x1B** [comment]
Update: I also get a validation failure when using a widget without any feature configuration (I now think that this also was the problem that I had with the layout). I think that we should always interpret a missing `features` block in a widget/composition/layout instance config as an empty object.

**Comment by x1B** [comment]
_Closing:_ #15 takes care of this
