### ISSUE TITLE
Fix incorrect theme path

### ISSUE THREAD

**Issue by jpommerening** [LaxarJS/laxar-tooling#16]
During refactoring, the default `styleSource` for themes got broken. It should be `css/theme.css`, but it has become `css/${themeName}.css` somehow.

**Comment by jpommerening** [comment]
Fixed on `master` (`v0.5.0-alpha.2`)

**Comment by x1B** [comment]
@jpommerening so this can be closed, I assume?

**Comment by jpommerening** [comment]
Whoopsie. Yes!
