### ISSUE TITLE
Strip schema information from artifacts

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar-tooling#18]
Because schemas are now validated and expanded by the page assembler, we can strip their information from the artifacts listing.

**Comment by jpommerening** [comment]
Shop Demo `app.bundle.min.js`
- before: 208431 bytes
- after: 200790 bytes

**Comment by jpommerening** [comment]
Implemented on `master` (`v2.0.0`)

### BREAKING CHANGE

Since the JSON schema validation now happens at build time, there is no need to have the schemas available in the application. Widget descriptors and pages contained in the artifact listing now have empty `features` properties.
