### ISSUE TITLE
make eslint part of npm test, fix linter problems

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar-tooling#31]
As with the other laxar projects, linting should become standard procedure.

**Comment by jpommerening** [comment]
Oh my god it's full of … warnings? :(

Looks like a typo in the `package.json` (`postTest` vs `posttest`)

**Comment by x1B** [comment]
@jpommerening ah, didn't catch that. Was under the impression that we just forgot linting completely here. Feel free to grab the issue if you're at this anyway (haven't done anything so far).

**Comment by jpommerening** [comment]
Maybe tomorrow ;)

**Comment by jpommerening** [comment]
Just a few lines, but they were good for a whole screen of eslint warnings.

Fixed on `master` (`v2.0.0`)
