### ISSUE TITLE
themes/widgets/controls/layouts: support preprocessed templates/styles

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar-tooling#6]
We'd like to support preprocessed styles (SCSS) to be supported directly by the LaxarJS toolchain. While at it, we probably want to add the same capabilities for templates (e.g. to support compile-time template-to-JS transforms, or compression).

_Idea:_
- add fields `"styleSource"` and `"templateSource"` to the descriptors of the above-mentioned artifacts.
- if missing, they default to `"css/${name}.css"` and `"${name}.html"` to reflect the current behavior.
- the tooling should load these assets as if specified under the lists `assetsForTheme` / `assetUrlsForTheme`. The explicit properties are needed so that no duplicate templates / styles are loaded.
- the runtime will query the artifact provider using `assetForTheme` and `assetUrlForTheme`, based on these properties.

**Comment by jpommerening** [comment]
### Upgrade info

Themes and layouts may now have "descriptor" the files `theme.json` and `layout.json` respectively.
These files are optional, but if they exist they _must_ at least have a `"name"` field, similar to widgets and controls.

Additionally, all descriptor files (`theme.json`, `layout.json`, `widget.json` and `control.json`) may now use the `"templateSource"` (except in themes) and `"styleSource"` fields to declare a different location for the default assets. (Details: LaxarJS/laxar#362)

The `"requireFile"` callback (`laxarTooling.assetListing.create()`) is called with either `json`, `content` (was: `raw`) or `url` as the second parameter, to reflect the structure of the artifact listing.

**Comment by jpommerening** [comment]
Implemented on `master` (`v0.4.0`)
